// Common
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const GET_SUCCESS = 'GET_SUCCESS';
export const CLEAR_INFO = 'CLEAR_INFO';

// Authentication
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_LOADING = 'AUTH_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

// Crawler
export const CRAWLER_GET_SUCCESS = 'CRAWLER_GET_SUCCESS';
export const CRAWLER_GET_FAIL = 'CRAWLER_GET_FAIL';
export const CRAWLER_GET_COUNT_SUCCESS = 'CRAWLER_GET_COUNT_SUCCESS';
export const CRAWLER_GET_COUNT_FAIL = 'CRAWLER_GET_COUNT_FAIL';
export const CRAWLER_LOADING = 'CRAWLER_LOADING';
